# Generated by Django 4.0.4 on 2022-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
