# Generated by Django 4.0.4 on 2022-07-10 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
